version: '3.9'

services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_SOURCE=${REACT_APP_API_SOURCE}
    command: ["npm", "start"]
