services:
  web:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
    restart: on-failure

  db:
    image: postgres:17.0
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  worker:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    container_name: worker
    depends_on:
      - rabbitmq
      - web
    environment:
      - RABBITMQ_HOST=rabbitmq
