version: '3.8'

services:
  web:
    build:
      context: ./app
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - kafka
    volumes:
      - "./app:/app"
    restart: on-failure

  db:
    image: postgres:17.0
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
  kafka:
    image: bitnami/kafka:3.8.0
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"

  worker:
    build:
      context: ./worker
    volumes:
      - "./worker:/app"
    container_name: kafka_worker
    depends_on:
      - kafka
      - web

  agent:
    build:
      context: ./agent
    volumes:
      - "./agent:/app"
    container_name: kafka_agent
    depends_on:
      - kafka
      - web
