version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
    volumes:
      - .:/app
    restart: on-failure

  db:
    image: postgres:17.0
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
  #   environment:
  #     ALLOW_PLAINTEXT_LISTENER: "yes"
  #   ports:
  #     - "9092:9092"
  #   depends_on:
  #     - zookeeper

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672" # RabbitMQ Management UI
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
  # zookeeper:
  #   image: bitnami/zookeeper:latest
  #   container_name: zookeeper
  #   environment:
  #     ALLOW_ANONYMOUS_LOGIN: "yes"
  #   ports:
  #     - "2181:2181"

  worker:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    volumes:
      - .:/app
    container_name: worker
    depends_on:
      - rabbitmq
      - web
    environment:
      - RABBITMQ_HOST=rabbitmq

  agent:
    build:
      context: ./
      dockerfile: ./agent/Dockerfile
    volumes:
      - .:/app
    container_name: agent
    ports:
      - "12345:12345"
    depends_on:
      - rabbitmq
      - web
    environment:
      - RABBITMQ_HOST=rabbitmq
