[project]
name = "j-pet-console-be"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []
[tool.black]
line-length = 79
[tool.isort]
profile = "black"
line_length = 79
