name: Deploy

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose


      - name: Set up OpenVPN
        run: |
          sudo apt-get update && sudo apt-get install -y openvpn
          echo "${{ vars.OPENVPN_CONFIG }}" > openvpn-config.ovpn
          echo "${{ secrets.OPENVPN_KEY }}" > openvpn.key
          echo "${{ secrets.OPENVPN_CERT }}" > openvpn.crt
          echo "${{ secrets.OPENVPN_CA }}" > ca.crt
          sudo openvpn --config openvpn-config.ovpn --daemon
        env:
          OPENVPN_CONFIG: ${{ vars.OPENVPN_CONFIG }}

      - name: Set up SSH tunnel
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
          chmod 600 ssh_key
          ssh -i ssh_key -o StrictHostKeyChecking=no -L 2375:localhost:2375 ${{ secrets.SSH_USER }}@${{ secrets.REMOTE_SERVER }} -N &
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USER: ${{ secrets.SSH_USER }}

      # Step 5: Build and deploy Docker Compose services
      - name: Deploy Docker Compose stack
        run: |
          export DOCKER_HOST=tcp://localhost:2375
          docker-compose -f docker-compose.yaml up -d
