name: backend
on:
  workflow_dispatch:
jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true # Recursively fetch all submodules
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - name: Set up OpenVPN
        run: |
          sudo apt-get update && sudo apt-get install -y openvpn
          echo "${{ vars.OPENVPN_CONFIG }}" > openvpn-config.ovpn
          echo "${{ secrets.OPENVPN_KEY }}" > openvpn.key
          echo "${{ secrets.OPENVPN_CERT }}" > openvpn.crt
          echo "${{ secrets.OPENVPN_CA }}" > ca.crt
          # sudo openvpn --config openvpn-config.ovpn --daemon
        env:
          OPENVPN_CONFIG: ${{ vars.OPENVPN_CONFIG }}

      - name: Start VPN
        run: |
          sudo openvpn --config openvpn-config.ovpn --daemon --log openvpn.log --writepid openvpn.pid

      - name: Set up SSH tunnel
        run: |
          mkdir ~/.ssh
          ssh-keyscan -H ${{ secrets.REMOTE_SERVER }} >> ~/.ssh/known_hosts
          eval `ssh-agent -s`
          ssh-add - <<< "${{secrets.SSH_PRIVATE_KEY}}"
          ssh -o ServerAliveInterval=60 -o ServerAliveCountMax=3 -fN -L 2375:localhost:2375 ${{ secrets.SSH_USER }}@${{ secrets.REMOTE_SERVER }}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USER: ${{ secrets.SSH_USER }}
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Deploy Docker Compose stack
        env:
          DOCKER_HOST: tcp://localhost:2375
        run: |
          echo "${{ secrets.DEPLOY_VARIABLES }}" > custom.env
          docker-compose --env-file custom.env -f docker-compose.yaml down
          docker-compose --env-file custom.env -f docker-compose.yaml up -d --build

      - name: Disconnect VPN
        if: always()
        run: |
          if [ -f openvpn.pid ]; then
            sudo kill -SIGTERM $(cat openvpn.pid)
            echo "VPN disconnected."
          else
            echo "No VPN PID found."
          fi
      - name: Make VPN log accessible
        if: always()
        run: |
          sudo chown $USER:$USER openvpn.log
      - name: Upload VPN log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: vpn-log
          path: openvpn.log
