name: Deploy

on:
  workflow_dispatch:
jobs:
  vpn-connection:
    uses: ./.github/workflows/vpn-connection.yml  # Path to the reusable workflow

  deploy:
    runs-on: ubuntu-latest
    needs: vpn-connection
    steps:
      - name: Deploy Docker Compose stack
        env:
          DOCKER_HOST: tcp://localhost:2375
        run: |
          echo "${{ secrets.DEPLOY_VARIABLES }}" > custom.env
          docker-compose --env-file custom.env -f docker-compose.yaml down -v
          docker-compose --env-file custom.env -f docker-compose.yaml up -d --build

      - name: Initialize submodules and front-end
        env:
          DOCKER_HOST: tcp://localhost:2375
        run: |
          git submodule init
          git submodule update --remote --recursive
          cd j-pet-console-fe
          echo "${{ secrets.DEPLOY_VARIABLES }}" > custom.env
          docker-compose --env-file custom.env -f docker-compose.yml down -v
          docker-compose --env-file custom.env -f docker-compose.yml up -d --build
