name: Deploy

on:
  workflow_dispatch:
jobs:
  connect:
    uses: ./.github/workflows/connec.yml  # Path to the reusable workflow

  deploy:
    runs-on: ubuntu-latest
    needs: connect
    steps:
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Deploy Docker Compose stack
        env:
          DOCKER_HOST: tcp://localhost:2375
        run: |
          echo "${{ secrets.DEPLOY_VARIABLES }}" > custom.env
          docker-compose --env-file custom.env -f docker-compose.yaml down -v
          docker-compose --env-file custom.env -f docker-compose.yaml up -d --build

      - name: Initialize submodules and front-end
        env:
          DOCKER_HOST: tcp://localhost:2375
        run: |
          git submodule init
          git submodule update --remote --recursive
          cd j-pet-console-fe
          echo "${{ secrets.DEPLOY_VARIABLES }}" > custom.env
          docker-compose --env-file custom.env -f docker-compose.yml down -v
          docker-compose --env-file custom.env -f docker-compose.yml up -d --build
