name: Test Docker Compose Build

on:
  push:
    paths:
      - 'agent/Dockerfile'
      - 'worker/Dockerfile'
      - 'backend/Dockerfile'
      - 'docker-compose.yaml'
      - 'docker-compose.prod.yaml'
      - 'docker-compose.local.yaml'
    branches:
      - main
      - JPC-44-compose-automatic-deployment
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Build Docker Compose services
        run: docker-compose -f docker-compose.yaml build
