name: Test Docker Compose Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (optional, for advanced features)
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      - name: Build Docker Compose services
        run: |
          docker-compose -f docker-compose.yml build
